service: jisshu-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  architecture: x86_64
  stage: dev
  region: us-east-1
  httpApi:
    cors:
      allowedOrigins:
        - https://omochifestival.com/
        - https://misskey.io/
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - PUT
        - POST
      allowCredentials: true
      exposedResponseHeaders:
        - Special-Response-Header
      maxAge: 6000

package:
  patterns:
    - "!**"
    - "src/**"

functions:
  service:
    handler: src.main.handler
    events:
      - http:
          path: /{path+}
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerImage: public.ecr.aws/sam/build-python3.11:latest-x86_64
    dockerizePip: true
