name: actions-serverless

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd serverless/ && npm ci && serverless deploy"
          entrypoint: /bin/bash
