name: Deploy branch

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      INIAD_OPENAI_API_KEY: ${{ secrets.INIAD_OPENAI_API_KEY }}
      APP_ENV: "ACTION"
      REDIS_HOST: "localhost"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1
      - name: Start Redis
        run: redis-server &
      - name: Run tests
        run: bash test.sh

  deploy:
    if: github.event_name == 'push'
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install Serverless Python Requirements Plugin
        run: serverless plugin install --name serverless-python-requirements
      - name: Deploy Serverless Service to Dev
        if: github.ref == 'refs/heads/dev'
        run: serverless deploy --verbose --config serverless.yml --stage dev
      - name: Deploy Serverless Service to Master
        if: github.ref == 'refs/heads/master'
        run: serverless deploy --verbose --config serverless.yml --stage master
