name: Deploy dev branch

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      INIAD_OPENAI_API_KEY: ${{ secrets.INIAD_OPENAI_API_KEY }}
      APP_ENV: "DEV"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: bash test.sh

  deploy:
    if: github.event_name == 'push'
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install Serverless Python Requirements Plugin
        run: serverless plugin install --name serverless-python-requirements
      - name: Check for changes in serverless.yml
        id: diff-check
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'serverless.yml'
          if [ $? -eq 0 ]; then
            echo "::set-output name=deploy_cmd::serverless deploy --verbose --config serverless.yml"
          else
            echo "::set-output name=deploy_cmd::serverless deploy function --verbose --config serverless.yml"
          fi
      - name: Deploy Serverless Service
        run: ${{ steps.diff-check.outputs.deploy_cmd }}